#ifndef SHADER_UNIFORMS_H
#define SHADER_UNIFORMS_H

namespace ShaderUniforms{
	enum{MVP,MODEL,STEP_SIZE,LIGHT_COLOR,LIGHT_DIRECTION,LIGHT_DIRECTIONAL,NUM_DIRECTIONAL_LIGHTS,NUM_UNIFORMS};

	
}

#endif